package com.wuhu.meizujdbc.dao;

import com.wuhu.meizubeans.pojo.TbColor;


import java.util.List;
public interface TbColorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_color
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_color
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int insert(TbColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_color
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    TbColor selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_color
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    List<TbColor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_color
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int updateByPrimaryKey(TbColor record);

    /**
     * 根据手机的Id查询对应的颜色
     * @param pid
     * @return
     */
    List<TbColor> getColorsByPid(Integer pid);
}