package com.wuhu.meizujdbc.dao;

import com.wuhu.meizubeans.pojo.TbImage;
import com.wuhu.meizubeans.pojo.TbShopping;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface TbImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_image
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int deleteByPrimaryKey(Integer iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_image
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int insert(TbShopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_image
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    TbImage selectByPrimaryKey(Integer iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_image
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    List<TbImage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_image
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int updateByPrimaryKey(TbImage record);

    /**
     * 根据cid查询对应的所有图片
     * @param cid
     * @return
     */
    List<TbImage> getImagesByCid(Integer cid);


}