package com.wuhu.meizujdbc.dao;

import com.wuhu.meizubeans.pojo.TbOrdersDetail;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface TbOrdersDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orders_detail
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int deleteByPrimaryKey(Integer odid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orders_detail
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int insert(TbOrdersDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orders_detail
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    TbOrdersDetail selectByPrimaryKey(Integer odid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orders_detail
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    List<TbOrdersDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orders_detail
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int updateByPrimaryKey(TbOrdersDetail record);
}