package com.wuhu.meizujdbc.dao;

import com.wuhu.meizubeans.pojo.TbOrders;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface TbOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orders
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int deleteByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orders
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int insert(TbOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orders
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    TbOrders selectByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orders
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    List<TbOrders> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orders
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int updateByPrimaryKey(TbOrders record);
}