package com.wuhu.meizujdbc.dao;

import com.wuhu.meizubeans.pojo.TbPhones;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.context.annotation.Configuration;

import java.util.List;
@Mapper
public interface TbPhonesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phones
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phones
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int insert(TbPhones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phones
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    TbPhones selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phones
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    List<TbPhones> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phones
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    int updateByPrimaryKey(TbPhones record);
}