package com.wuhu.meizubeans.pojo;

import java.util.List;

public class TbColor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_color.cid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_color.colorname
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private String colorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_color.pid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer pid;
    /**
     * 一个颜色对应多张图片
     */
    private List<TbImage> imageList;

    public List<TbImage> getImageList() {
        return imageList;
    }

    public void setImageList(List<TbImage> imageList) {
        this.imageList = imageList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_color.cid
     *
     * @return the value of tb_color.cid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_color.cid
     *
     * @param cid the value for tb_color.cid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_color.colorname
     *
     * @return the value of tb_color.colorname
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public String getColorname() {
        return colorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_color.colorname
     *
     * @param colorname the value for tb_color.colorname
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setColorname(String colorname) {
        this.colorname = colorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_color.pid
     *
     * @return the value of tb_color.pid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_color.pid
     *
     * @param pid the value for tb_color.pid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}