package com.wuhu.meizubeans.pojo;

public class TbImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.iid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer iid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.cid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.url
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.iid
     *
     * @return the value of tb_image.iid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.iid
     *
     * @param iid the value for tb_image.iid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setIid(Integer iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.cid
     *
     * @return the value of tb_image.cid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.cid
     *
     * @param cid the value for tb_image.cid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.url
     *
     * @return the value of tb_image.url
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.url
     *
     * @param url the value for tb_image.url
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setUrl(String url) {
        this.url = url;
    }
}