package com.wuhu.meizubeans.pojo;

public class TbOrdersDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orders_detail.odid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer odid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orders_detail.oid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orders_detail.pid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orders_detail.num
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orders_detail.aid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer aid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orders_detail.odid
     *
     * @return the value of tb_orders_detail.odid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getOdid() {
        return odid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orders_detail.odid
     *
     * @param odid the value for tb_orders_detail.odid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setOdid(Integer odid) {
        this.odid = odid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orders_detail.oid
     *
     * @return the value of tb_orders_detail.oid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orders_detail.oid
     *
     * @param oid the value for tb_orders_detail.oid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orders_detail.pid
     *
     * @return the value of tb_orders_detail.pid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orders_detail.pid
     *
     * @param pid the value for tb_orders_detail.pid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orders_detail.num
     *
     * @return the value of tb_orders_detail.num
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orders_detail.num
     *
     * @param num the value for tb_orders_detail.num
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orders_detail.aid
     *
     * @return the value of tb_orders_detail.aid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orders_detail.aid
     *
     * @param aid the value for tb_orders_detail.aid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }
}