package com.wuhu.meizubeans.pojo;

import java.util.List;

public class TbPhones {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phones.pid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phones.phonename
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private String phonename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phones.baseprice
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Double baseprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phones.mid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phones.image
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phones.title
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private String title;

    /**
     * 添加颜色集合属性
     */
    private List<TbColor> colors;

    public List<TbColor> getColors() {
        return colors;
    }

    public void setColors(List<TbColor> colors) {
        this.colors = colors;
    }

    /**
     * 此手机当前颜色的下标
     */
    private int colorIndex = 0;

    public int getColorIndex() {
        return colorIndex;
    }

    public void setColorIndex(int colorIndex) {
        this.colorIndex = colorIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phones.pid
     *
     * @return the value of tb_phones.pid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phones.pid
     *
     * @param pid the value for tb_phones.pid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phones.phonename
     *
     * @return the value of tb_phones.phonename
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public String getPhonename() {
        return phonename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phones.phonename
     *
     * @param phonename the value for tb_phones.phonename
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setPhonename(String phonename) {
        this.phonename = phonename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phones.baseprice
     *
     * @return the value of tb_phones.baseprice
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Double getBaseprice() {
        return baseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phones.baseprice
     *
     * @param baseprice the value for tb_phones.baseprice
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setBaseprice(Double baseprice) {
        this.baseprice = baseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phones.mid
     *
     * @return the value of tb_phones.mid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phones.mid
     *
     * @param mid the value for tb_phones.mid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phones.image
     *
     * @return the value of tb_phones.image
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phones.image
     *
     * @param image the value for tb_phones.image
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_phones.title
     *
     * @return the value of tb_phones.title
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_phones.title
     *
     * @param title the value for tb_phones.title
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }
}