package com.wuhu.meizubeans.pojo;

public class TbShopping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shopping.sid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shopping.pid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shopping.num
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    private Integer num;

    /**
     * 添加手机属性
     */
    private TbPhones tbPhones;

    public TbPhones getTbPhones() {
        return tbPhones;
    }

    public void setTbPhones(TbPhones tbPhones) {
        this.tbPhones = tbPhones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shopping.sid
     *
     * @return the value of tb_shopping.sid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shopping.sid
     *
     * @param sid the value for tb_shopping.sid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shopping.pid
     *
     * @return the value of tb_shopping.pid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shopping.pid
     *
     * @param pid the value for tb_shopping.pid
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shopping.num
     *
     * @return the value of tb_shopping.num
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shopping.num
     *
     * @param num the value for tb_shopping.num
     *
     * @mbg.generated Thu Jul 08 20:44:10 CST 2021
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}